---
kinematics:
  incoming_momenta: [p1,p2]
  outgoing_momenta: [p3,p4,q]
  momentum_conservation: [q,p1+p2-p3-p4]
  kinematic_invariants:
    - [s13,2]
    - [s34,2]
    - [s24,2]
    - [s25,2]
    - [s51,2]
    - [mt,1]
    - [mh,1]
  scalarproduct_rules:
    - [[p1,p1],0]
    - [[p2,p2],0]
    - [[p3,p3],mt^2]
    - [[p4,p4],mt^2]
    - [[q,q],mh^2]
    - [[p1-p3,p1-p3],s13]
    - [[p3+p4,p3+p4],s34]
    - [[p2-p4,p2-p4],s24]
    - [[p2-q,p2-q],s25]
    - [[p1-q,p1-q],s51]
