#define rule1 "0"
#define rule2 "0"
#define rule3 "0"
#define rule4 "0"
#define rule5 "0"
#define rule6 "0"
#define rule7 "0"
#define rule8 "0"
#define rule9 "0"
#define rule10 "0"
#define rule11 "0"
#define rule12 "0"
#define rule13 "0"
#define rule14 "0"
#define rule15 "0"
#define rule16 "0"
#define rule17 "0"
#define rule18 "0"
#define rule19 "0"
#define rule20 "0"
#define rule21 "0"
#define rule22 "0"
#define rule23 "0"
#define rule24 "0"
#define rule25 "0"
#define rule26 "0"
#define rule27 "0"
#define rule28 "0"
#define rule29 "0"
#define rule30 "0"
#define rule31 "0"
#define rule32 "0"
#define rule33 "0"
#define rule34 "0"
#define rule35 "0"
#define rule36 "0"
#define rule37 "0"
#define rule38 "0"
#define rule39 "0"
#define rule40 "0"
#define rule41 "0"
#define rule42 "0"
#define rule43 "0"
#define rule44 "0"
#define rule45 "0"
#define rule46 "0"
#define rule47 "0"
#define rule48 "0"
#define rule49 "0"
#define rule50 "0"
#define rule51 "0"
#define rule52 "0"
#define rule53 "0"
#define rule54 "0"
#define rule55 "0"
#define rule56 "0"
#define rule57 "0"
#define rule58 "0"
#define rule59 "0"
#define rule60 "0"
#define rule61 "0"
#define rule62 "0"
#define rule63 "0"
#define rule64 "0"
#define rule65 "0"
#define rule66 "0"
#define rule67 "0"
#define rule68 "0"
#define rule69 "0"
#define rule70 "0"
#define rule71 "0"
#define rule72 "0"
#define rule73 "0"
#define rule74 "0"
#define rule75 "0"
#define rule76 "0"
#define rule77 "0"
#define rule78 "0"
#define rule79 "0"
#define rule80 "0"
#define rule81 "0"
#define rule82 "0"
#define rule83 "0"
#define rule84 "0"
#define rule85 "0"
#define rule86 "0"
#define rule87 "0"
#define rule88 "0"
#define rule89 "0"
#define rule90 "0"
#define rule91 "0"
#define rule92 "0"
#define rule93 "0"
#define rule94 "0"
#define rule95 "0"
#define rule96 "0"
#define rule97 "0"
#define rule98 "0"
#define rule99 "0"
#define rule100 "0"
#define rule101 "0"
#define rule102 "0"
#define rule103 "0"
#define rule104 "0"
#define rule105 "0"
#define rule106 "0"
#define rule107 "0"
#define rule108 "0"
#define rule109 "0"
#define rule110 "0"
#define rule111 "0"
#define rule112 "0"
#define rule113 "0"
#define rule114 "0"
#define rule115 "0"
#define rule116 "0"
#define rule117 "0"
#define rule118 "0"
#define rule119 "0"
#define rule120 "0"
#define rule121 "0"
#define rule122 "0"
#define rule123 "0"
#define rule124 "0"
#define rule125 "0"
#define rule126 "0"
#define rule127 "0"
#define rule128 "0"
#define rule129 "0"
#define rule130 "0"
#define rule131 "0"
#define rule132 "0"
#define rule133 "0"
#define rule134 "0"
#define rule135 "0"
#define rule136 "0"
#define rule137 "0"
#define rule138 "0"
#define rule139 "0"
#define rule140 "0"
#define rule141 "0"
#define rule142 "0"
#define rule143 "0"
#define rule144 "0"
#define rule145 "0"
#define rule146 "0"
#define rule147 "0"
#define rule148 "0"
#define rule149 "0"
#define rule150 "0"
#define rule151 "0"
#define rule152 "0"
#define rule153 "0"
#define rule154 "0"
#define rule155 "0"
#define rule156 "0"
#define rule157 "0"
#define rule158 "0"
#define rule159 "0"
#define rule160 "0"
#define rule161 "0"
#define rule162 "0"
#define rule163 "0"
#define rule164 "0"
#define rule165 "0"
#define rule166 "0"
#define rule167 "0"
#define rule168 "0"
#define rule169 "0"
#define rule170 "0"
#define rule171 "0"
#define rule172 "0"
#define rule173 "0"
#define rule174 "0"
#define rule175 "0"
#define rule176 "0"
#define rule177 "0"
#define rule178 "0"
#define rule179 "0"
#define rule180 "0"
#define rule181 "0"
#define rule182 "0"
#define rule183 "0"
#define rule184 "0"
#define rule185 "0"
#define rule186 "0"
#define rule187 "0"
#define rule188 "0"
#define rule189 "0"
#define rule190 "0"
#define rule191 "0"
#define rule192 "0"
#define rule193 "0"
#define rule194 "0"
#define rule195 "0"
#define rule196 "0"
#define rule197 "0"
#define rule198 "0"
#define rule199 "0"
#define rule200 "0"
#define rule201 "0"
#define rule202 "0"
#define rule203 "0"
#define rule204 "0"
#define rule205 "0"
#define rule206 "0"
#define rule207 "0"
#define rule208 "0"
#define rule209 "0"
#define rule210 "0"
#define rule211 "0"
#define rule212 "0"
#define rule213 "0"
#define rule214 "0"
#define rule215 "0"
#define rule216 "0"
#define rule217 "0"
#define rule218 "0"
#define rule219 "0"
#define rule220 "0"
#define rule221 "0"
#define rule222 "0"
#define rule223 "0"
#define rule224 "0"
#define rule225 "0"
#define rule226 "0"
#define rule227 "0"
#define rule228 "0"
if (match(mt*q2));
 redefine rule1 "1";
 $repeat = 1;
endif;
if (match(d*q1));
 redefine rule2 "1";
 $repeat = 1;
endif;
if (match(mh*q3*q4));
 redefine rule3 "1";
 $repeat = 1;
endif;
if (match(mh*q6*q7));
 redefine rule4 "1";
 $repeat = 1;
endif;
if (match(q4*q6*q7));
 redefine rule5 "1";
 $repeat = 1;
endif;
if (match(q3*q6*s45));
 redefine rule6 "1";
 $repeat = 1;
endif;
if (match(q4*q7*s45));
 redefine rule7 "1";
 $repeat = 1;
endif;
if (match(mh^2*q3));
 redefine rule8 "1";
 $repeat = 1;
endif;
if (match(mh^2*q4));
 redefine rule9 "1";
 $repeat = 1;
endif;
if (match(mh^2*q6));
 redefine rule10 "1";
 $repeat = 1;
endif;
if (match(mh*mt*q4*q6));
 redefine rule11 "1";
 $repeat = 1;
endif;
if (match(q2*q4*q6*s45));
 redefine rule12 "1";
 $repeat = 1;
endif;
if (match(mh^2*q7));
 redefine rule13 "1";
 $repeat = 1;
endif;
if (match(mh*mt*q3*q7));
 redefine rule14 "1";
 $repeat = 1;
endif;
if (match(q2*q3*q7*s45));
 redefine rule15 "1";
 $repeat = 1;
endif;
if (match(mt^2*q3*q4));
 redefine rule16 "1";
 $repeat = 1;
endif;
if (match(q2*q3*q4*s45));
 redefine rule17 "1";
 $repeat = 1;
endif;
if (match(mt^2*q6*q7));
 redefine rule18 "1";
 $repeat = 1;
endif;
if (match(q2*q6*q7*s53));
 redefine rule19 "1";
 $repeat = 1;
endif;
if (match(mt^4*q5));
 redefine rule20 "1";
 $repeat = 1;
endif;
if (match(q2*q5*s12^2));
 redefine rule21 "1";
 $repeat = 1;
endif;
if (match(q2*q3*q4*q6*s53));
 redefine rule22 "1";
 $repeat = 1;
endif;
if (match(q2*q3*q4*q7*s53));
 redefine rule23 "1";
 $repeat = 1;
endif;
if (match(mt^4*q8));
 redefine rule24 "1";
 $repeat = 1;
endif;
if (match(q2*q8*s12^2));
 redefine rule25 "1";
 $repeat = 1;
endif;
if (match(mt^2*q5*q8*s45));
 redefine rule26 "1";
 $repeat = 1;
endif;
if (match(q2*q5*q8*s12*s45));
 redefine rule27 "1";
 $repeat = 1;
endif;
if (match(mt^3*q4*q6));
 redefine rule28 "1";
 $repeat = 1;
endif;
if (match(mt^3*q3*q7));
 redefine rule29 "1";
 $repeat = 1;
endif;
if (match(q3*q6*q8));
 redefine rule30 "1";
 $repeat = 1;
endif;
if (match(q4*q7*q8));
 redefine rule31 "1";
 $repeat = 1;
endif;
if (match(q2*q5*q8*s45^3));
 redefine rule32 "1";
 $repeat = 1;
endif;
if (match(q3*q4*q5*s12^2));
 redefine rule33 "1";
 $repeat = 1;
endif;
if (match(q6*q7*q8*s12^2));
 redefine rule34 "1";
 $repeat = 1;
endif;
if (match(q3*q4*q5*q8*s12*s45));
 redefine rule35 "1";
 $repeat = 1;
endif;
if (match(q2*q3*q4*q5*q8*s12*s53));
 redefine rule36 "1";
 $repeat = 1;
endif;
if (match(q5*q6*q7*q8*s12*s45));
 redefine rule37 "1";
 $repeat = 1;
endif;
if (match(q5*q8*s12^2*s45));
 redefine rule38 "1";
 $repeat = 1;
endif;
if (match(mt^2*q4*q5*q6*s12));
 redefine rule39 "1";
 $repeat = 1;
endif;
if (match(mt^2*q3*q5*q7*s12));
 redefine rule40 "1";
 $repeat = 1;
endif;
if (match(mh^2*mt^4*q9));
 redefine rule41 "1";
 $repeat = 1;
endif;
if (match(mh^4*q2*q9*s12));
 redefine rule42 "1";
 $repeat = 1;
endif;
if (match(mh*q4*q5*q6*s12^2));
 redefine rule43 "1";
 $repeat = 1;
endif;
if (match(mh*q3*q5*q7*s12^2));
 redefine rule44 "1";
 $repeat = 1;
endif;
if (match(q5*q6*q7*s12^2));
 redefine rule45 "1";
 $repeat = 1;
endif;
if (match(q3*q4*q8*s12^2));
 redefine rule46 "1";
 $repeat = 1;
endif;
if (match(mt^2*q4*q6*q8));
 redefine rule47 "1";
 $repeat = 1;
endif;
if (match(q2*q4*q6*q8*s12));
 redefine rule48 "1";
 $repeat = 1;
endif;
if (match(mt^2*q3*q7*q8));
 redefine rule49 "1";
 $repeat = 1;
endif;
if (match(q2*q3*q7*q8*s12));
 redefine rule50 "1";
 $repeat = 1;
endif;
if (match(mt*q4*q5*q6*s12^2));
 redefine rule51 "1";
 $repeat = 1;
endif;
if (match(mt*q3*q5*q7*s12^2));
 redefine rule52 "1";
 $repeat = 1;
endif;
if (match(q2*q6*q9*s12^2*s53));
 redefine rule53 "1";
 $repeat = 1;
endif;
if (match(mh*mt^5*q6*q9));
 redefine rule54 "1";
 $repeat = 1;
endif;
if (match(q2*q7*q9*s12^2*s53));
 redefine rule55 "1";
 $repeat = 1;
endif;
if (match(mh*mt^5*q7*q9));
 redefine rule56 "1";
 $repeat = 1;
endif;
if (match(mh*mt^5*q3*q9));
 redefine rule57 "1";
 $repeat = 1;
endif;
if (match(q2*q3*q9*s12^2*s45));
 redefine rule58 "1";
 $repeat = 1;
endif;
if (match(mh*mt^5*q4*q9));
 redefine rule59 "1";
 $repeat = 1;
endif;
if (match(q2*q4*q9*s12^2*s45));
 redefine rule60 "1";
 $repeat = 1;
endif;
if (match(mh^4*q5*q9*s12));
 redefine rule61 "1";
 $repeat = 1;
endif;
if (match(mh^4*q8*q9*s12));
 redefine rule62 "1";
 $repeat = 1;
endif;
if (match(mh*q4*q6*q8*s12));
 redefine rule63 "1";
 $repeat = 1;
endif;
if (match(mh*q3*q7*q8*s12));
 redefine rule64 "1";
 $repeat = 1;
endif;
if (match(q2*q3*q4*q9*s53^2));
 redefine rule65 "1";
 $repeat = 1;
endif;
if (match(mh*q2*q5*q6*q9*s12*s45));
 redefine rule66 "1";
 $repeat = 1;
endif;
if (match(mh*mt^2*q5*q6*q9*s12));
 redefine rule67 "1";
 $repeat = 1;
endif;
if (match(mh*q2*q5*q7*q9*s12*s45));
 redefine rule68 "1";
 $repeat = 1;
endif;
if (match(mh*mt^2*q5*q7*q9*s12));
 redefine rule69 "1";
 $repeat = 1;
endif;
if (match(q3*q4*q9*s45^2));
 redefine rule70 "1";
 $repeat = 1;
endif;
if (match(mh*q2*q5*q6*q8*q9*s45^2));
 redefine rule71 "1";
 $repeat = 1;
endif;
if (match(mh*q2*q5*q7*q8*q9*s45^2));
 redefine rule72 "1";
 $repeat = 1;
endif;
if (match(q2*q3*q5*q9*s12*s45^2));
 redefine rule73 "1";
 $repeat = 1;
endif;
if (match(q2*q4*q5*q9*s12*s45^2));
 redefine rule74 "1";
 $repeat = 1;
endif;
if (match(mt*q4*q6*q8*s12));
 redefine rule75 "1";
 $repeat = 1;
endif;
if (match(mt*q3*q7*q8*s12));
 redefine rule76 "1";
 $repeat = 1;
endif;
if (match(q3*q4*q5*q8*s45^3));
 redefine rule77 "1";
 $repeat = 1;
endif;
if (match(q5*q6*q7*q8*s45^3));
 redefine rule78 "1";
 $repeat = 1;
endif;
if (match(mh*q4*q5*q6*q8*s45));
 redefine rule79 "1";
 $repeat = 1;
endif;
if (match(q2*q4*q5*q6*q8*s53));
 redefine rule80 "1";
 $repeat = 1;
endif;
if (match(mh*q3*q5*q7*q8*s45));
 redefine rule81 "1";
 $repeat = 1;
endif;
if (match(q2*q3*q5*q7*q8*s53));
 redefine rule82 "1";
 $repeat = 1;
endif;
if (match(mh*mt^3*q3*q5*q9*s12));
 redefine rule83 "1";
 $repeat = 1;
endif;
if (match(mh*mt^3*q4*q5*q9*s12));
 redefine rule84 "1";
 $repeat = 1;
endif;
if (match(q2*q3*q4*q5*q8*s53^3));
 redefine rule85 "1";
 $repeat = 1;
endif;
if (match(mh*mt^3*q6*q8*q9*s12));
 redefine rule86 "1";
 $repeat = 1;
endif;
if (match(mh*mt^3*q7*q8*q9*s12));
 redefine rule87 "1";
 $repeat = 1;
endif;
if (match(mh*mt^2*q3*q5*q9*s12*s45));
 redefine rule88 "1";
 $repeat = 1;
endif;
if (match(mh*mt^2*q4*q5*q9*s12*s45));
 redefine rule89 "1";
 $repeat = 1;
endif;
if (match(mt^7*q3*q9));
 redefine rule90 "1";
 $repeat = 1;
endif;
if (match(mt^7*q4*q9));
 redefine rule91 "1";
 $repeat = 1;
endif;
if (match(mt^7*q6*q9));
 redefine rule92 "1";
 $repeat = 1;
endif;
if (match(q2*q5*q6*q9*s12*s45*s53));
 redefine rule93 "1";
 $repeat = 1;
endif;
if (match(mt^7*q7*q9));
 redefine rule94 "1";
 $repeat = 1;
endif;
if (match(q2*q5*q7*q9*s12*s45*s53));
 redefine rule95 "1";
 $repeat = 1;
endif;
if (match(mt^2*q4*q5*q6*s45^2));
 redefine rule96 "1";
 $repeat = 1;
endif;
if (match(mt^2*q3*q5*q7*s45^2));
 redefine rule97 "1";
 $repeat = 1;
endif;
if (match(mh*mt^2*q3*q5*q9*s12^2));
 redefine rule98 "1";
 $repeat = 1;
endif;
if (match(mh*mt^2*q4*q5*q9*s12^2));
 redefine rule99 "1";
 $repeat = 1;
endif;
if (match(mh*mt^3*q5*q6*q9*s45));
 redefine rule100 "1";
 $repeat = 1;
endif;
if (match(mh*mt^3*q5*q7*q9*s45));
 redefine rule101 "1";
 $repeat = 1;
endif;
if (match(mh^4*q2*q5*q9*s45^2));
 redefine rule102 "1";
 $repeat = 1;
endif;
if (match(mh*mt^2*q6*q8*q9*s12^2));
 redefine rule103 "1";
 $repeat = 1;
endif;
if (match(mh*mt^2*q7*q8*q9*s12^2));
 redefine rule104 "1";
 $repeat = 1;
endif;
if (match(mh^4*q2*q8*q9*s53^2));
 redefine rule105 "1";
 $repeat = 1;
endif;
if (match(q4*q5*q6*q8*s12));
 redefine rule106 "1";
 $repeat = 1;
endif;
if (match(q3*q5*q7*q8*s12));
 redefine rule107 "1";
 $repeat = 1;
endif;
if (match(mh*mt*q5*q6*q9*s12*s45));
 redefine rule108 "1";
 $repeat = 1;
endif;
if (match(mh*mt*q5*q7*q9*s12*s45));
 redefine rule109 "1";
 $repeat = 1;
endif;
if (match(mh*mt*q3*q5*q9*s45^3));
 redefine rule110 "1";
 $repeat = 1;
endif;
if (match(mh*mt*q4*q5*q9*s45^3));
 redefine rule111 "1";
 $repeat = 1;
endif;
if (match(q2*q5*q6*q9*s12*s45^2));
 redefine rule112 "1";
 $repeat = 1;
endif;
if (match(q2*q5*q7*q9*s12*s45^2));
 redefine rule113 "1";
 $repeat = 1;
endif;
if (match(mh*mt^3*q3*q5*q9*s45^2));
 redefine rule114 "1";
 $repeat = 1;
endif;
if (match(mh*mt^3*q4*q5*q9*s45^2));
 redefine rule115 "1";
 $repeat = 1;
endif;
if (match(q4*q5*q6*q8*s45*s53));
 redefine rule116 "1";
 $repeat = 1;
endif;
if (match(q3*q5*q7*q8*s45*s53));
 redefine rule117 "1";
 $repeat = 1;
endif;
if (match(q4*q6*q8*s12^2));
 redefine rule118 "1";
 $repeat = 1;
endif;
if (match(q3*q7*q8*s12^2));
 redefine rule119 "1";
 $repeat = 1;
endif;
if (match(mh*q4*q5*q6*q8*s53));
 redefine rule120 "1";
 $repeat = 1;
endif;
if (match(mh*q3*q5*q7*q8*s53));
 redefine rule121 "1";
 $repeat = 1;
endif;
if (match(mt^3*q5*q6*q9*s45^2));
 redefine rule122 "1";
 $repeat = 1;
endif;
if (match(mt^3*q5*q7*q9*s45^2));
 redefine rule123 "1";
 $repeat = 1;
endif;
if (match(q2*q3*q5*q9*s45^4));
 redefine rule124 "1";
 $repeat = 1;
endif;
if (match(q2*q4*q5*q9*s45^4));
 redefine rule125 "1";
 $repeat = 1;
endif;
if (match(mt^3*q3*q5*q9*s45^3));
 redefine rule126 "1";
 $repeat = 1;
endif;
if (match(mt^3*q4*q5*q9*s45^3));
 redefine rule127 "1";
 $repeat = 1;
endif;
if (match(mh*mt^2*q5*q6*q9*s45^2));
 redefine rule128 "1";
 $repeat = 1;
endif;
if (match(mh*mt^2*q5*q7*q9*s45^2));
 redefine rule129 "1";
 $repeat = 1;
endif;
if (match(mt^3*q5*q6*q9*s12*s45));
 redefine rule130 "1";
 $repeat = 1;
endif;
if (match(mt^3*q5*q7*q9*s12*s45));
 redefine rule131 "1";
 $repeat = 1;
endif;
if (match(mh*q2*q5*q6*q9*s12*s53^2));
 redefine rule132 "1";
 $repeat = 1;
endif;
if (match(mh*q2*q5*q7*q9*s12*s53^2));
 redefine rule133 "1";
 $repeat = 1;
endif;
if (match(mh^4*q5*q8*q9*s45^3));
 redefine rule134 "1";
 $repeat = 1;
endif;
if (match(q4*q5*q6*s12^4));
 redefine rule135 "1";
 $repeat = 1;
endif;
if (match(q3*q5*q7*s12^4));
 redefine rule136 "1";
 $repeat = 1;
endif;
if (match(mt^3*q3*q5*q9*s12^2*s45));
 redefine rule137 "1";
 $repeat = 1;
endif;
if (match(mt^3*q4*q5*q9*s12^2*s45));
 redefine rule138 "1";
 $repeat = 1;
endif;
if (match(q2*q3*q7*q9*s53));
 redefine rule139 "1";
 $repeat = 1;
endif;
if (match(mh*mt*q3*q5*q9*s12^3*s45));
 redefine rule140 "1";
 $repeat = 1;
endif;
if (match(q2*q5*q6*q9*s12*s53^3));
 redefine rule141 "1";
 $repeat = 1;
endif;
if (match(q2*q5*q7*q9*s12*s53^3));
 redefine rule142 "1";
 $repeat = 1;
endif;
if (match(mt^2*q5*q6*q9*s12^2*s45));
 redefine rule143 "1";
 $repeat = 1;
endif;
if (match(mt^2*q5*q7*q9*s12^2*s45));
 redefine rule144 "1";
 $repeat = 1;
endif;
if (match(mh*mt*q3*q5*q9*s12^2*s45^2));
 redefine rule145 "1";
 $repeat = 1;
endif;
if (match(mh*mt*q4*q5*q9*s12^2*s45^2));
 redefine rule146 "1";
 $repeat = 1;
endif;
if (match(mt^2*q5*q6*q9*s12*s45^2));
 redefine rule147 "1";
 $repeat = 1;
endif;
if (match(mt^2*q5*q7*q9*s12*s45^2));
 redefine rule148 "1";
 $repeat = 1;
endif;
if (match(mh*mt*q4*q5*q9*s12^3*s45));
 redefine rule149 "1";
 $repeat = 1;
endif;
if (match(q2*q3*q6*q9*s53));
 redefine rule150 "1";
 $repeat = 1;
endif;
if (match(q2*q4*q7*q9*s53));
 redefine rule151 "1";
 $repeat = 1;
endif;
if (match(q2*q4*q6*q9*s53));
 redefine rule152 "1";
 $repeat = 1;
endif;
if (match(q2*q6*q8*q9*s12*s53));
 redefine rule153 "1";
 $repeat = 1;
endif;
if (match(mt^2*q5*q6*q9*s45^3));
 redefine rule154 "1";
 $repeat = 1;
endif;
if (match(mt^2*q5*q7*q9*s45^3));
 redefine rule155 "1";
 $repeat = 1;
endif;
if (match(q3*q8*q9));
 redefine rule156 "1";
 $repeat = 1;
endif;
if (match(q4*q8*q9));
 redefine rule157 "1";
 $repeat = 1;
endif;
if (match(q2*q7*q8*q9*s12*s53));
 redefine rule158 "1";
 $repeat = 1;
endif;
if (match(mh*q3*q5*q9*s12^2*s45^3));
 redefine rule159 "1";
 $repeat = 1;
endif;
if (match(mh*q4*q5*q9*s12^2*s45^3));
 redefine rule160 "1";
 $repeat = 1;
endif;
if (match(mt^3*q5*q6*q9*s12^2*s53));
 redefine rule161 "1";
 $repeat = 1;
endif;
if (match(mt^3*q5*q7*q9*s12^2*s53));
 redefine rule162 "1";
 $repeat = 1;
endif;
if (match(q2*q6*q8*q9*s45^2*s53));
 redefine rule163 "1";
 $repeat = 1;
endif;
if (match(q2*q5*q6*q9*s45^4));
 redefine rule164 "1";
 $repeat = 1;
endif;
if (match(q2*q5*q7*q9*s45^4));
 redefine rule165 "1";
 $repeat = 1;
endif;
if (match(mt^3*q5*q6*q9*s12*s53^2));
 redefine rule166 "1";
 $repeat = 1;
endif;
if (match(mt^3*q5*q7*q9*s12*s53^2));
 redefine rule167 "1";
 $repeat = 1;
endif;
if (match(mh*q7*q8*q9*s53));
 redefine rule168 "1";
 $repeat = 1;
endif;
if (match(mt^2*q3*q5*q9*s12*s45^4));
 redefine rule169 "1";
 $repeat = 1;
endif;
if (match(mt^2*q4*q5*q9*s12*s45^4));
 redefine rule170 "1";
 $repeat = 1;
endif;
if (match(mt^2*q4*q6*q9));
 redefine rule171 "1";
 $repeat = 1;
endif;
if (match(mt^2*q3*q7*q9));
 redefine rule172 "1";
 $repeat = 1;
endif;
if (match(mh*mt*q3*q6*q9));
 redefine rule173 "1";
 $repeat = 1;
endif;
if (match(mh*q5*q6*q9*s12^2*s45^2));
 redefine rule174 "1";
 $repeat = 1;
endif;
if (match(mh*q5*q7*q9*s12^2*s45^2));
 redefine rule175 "1";
 $repeat = 1;
endif;
if (match(mt^2*q3*q5*q9*s12^2*s45^3));
 redefine rule176 "1";
 $repeat = 1;
endif;
if (match(mt^2*q4*q5*q9*s12^2*s45^3));
 redefine rule177 "1";
 $repeat = 1;
endif;
if (match(mt*q3*q5*q9*s12^2*s45^4));
 redefine rule178 "1";
 $repeat = 1;
endif;
if (match(mt*q4*q5*q9*s12^2*s45^4));
 redefine rule179 "1";
 $repeat = 1;
endif;
if (match(mh*mt*q5*q6*q9*s45^3*s53));
 redefine rule180 "1";
 $repeat = 1;
endif;
if (match(mh*mt*q5*q7*q9*s45^3*s53));
 redefine rule181 "1";
 $repeat = 1;
endif;
if (match(mt*q5*q6*q9*s12^2*s45^3));
 redefine rule182 "1";
 $repeat = 1;
endif;
if (match(mt*q5*q7*q9*s12^2*s45^3));
 redefine rule183 "1";
 $repeat = 1;
endif;
if (match(mt*q5*q6*q9*s12^3*s45^2));
 redefine rule184 "1";
 $repeat = 1;
endif;
if (match(mt*q5*q7*q9*s12^3*s45^2));
 redefine rule185 "1";
 $repeat = 1;
endif;
if (match(mt^3*q3*q6*q9));
 redefine rule186 "1";
 $repeat = 1;
endif;
if (match(mt^2*q6*q8*q9*s53));
 redefine rule187 "1";
 $repeat = 1;
endif;
if (match(mt^2*q3*q5*q9*s45^6));
 redefine rule188 "1";
 $repeat = 1;
endif;
if (match(mt^2*q4*q5*q9*s45^6));
 redefine rule189 "1";
 $repeat = 1;
endif;
if (match(q6*q8*q9*s53^2));
 redefine rule190 "1";
 $repeat = 1;
endif;
if (match(q7*q8*q9*s53^2));
 redefine rule191 "1";
 $repeat = 1;
endif;
if (match(mh*q3*q7*q9*s45));
 redefine rule192 "1";
 $repeat = 1;
endif;
if (match(mt^2*q7*q8*q9*s53));
 redefine rule193 "1";
 $repeat = 1;
endif;
if (match(q2*q5*q6*q8*q9*s45*s53));
 redefine rule194 "1";
 $repeat = 1;
endif;
if (match(q2*q5*q7*q8*q9*s45*s53));
 redefine rule195 "1";
 $repeat = 1;
endif;
if (match(mt^2*q3*q5*q6*q9*s12));
 redefine rule196 "1";
 $repeat = 1;
endif;
if (match(q2*q7*q8*q9*s45^2*s53));
 redefine rule197 "1";
 $repeat = 1;
endif;
if (match(q5*q6*q9*s12^4*s45^2));
 redefine rule198 "1";
 $repeat = 1;
endif;
if (match(q5*q7*q9*s12^4*s45^2));
 redefine rule199 "1";
 $repeat = 1;
endif;
if (match(mh*mt^3*q5*q7*q8*q9));
 redefine rule200 "1";
 $repeat = 1;
endif;
if (match(mh*mt^3*q5*q6*q8*q9));
 redefine rule201 "1";
 $repeat = 1;
endif;
if (match(q3*q7*q9*s45^2));
 redefine rule202 "1";
 $repeat = 1;
endif;
if (match(mh*q5*q7*q8*q9*s12*s45));
 redefine rule203 "1";
 $repeat = 1;
endif;
if (match(q3*q5*q9*s12^4*s45^4));
 redefine rule204 "1";
 $repeat = 1;
endif;
if (match(q4*q5*q9*s12^4*s45^4));
 redefine rule205 "1";
 $repeat = 1;
endif;
if (match(q5*q7*q8*q9*s12*s45*s53));
 redefine rule206 "1";
 $repeat = 1;
endif;
if (match(mh*q5*q6*q8*q9*s12*s45));
 redefine rule207 "1";
 $repeat = 1;
endif;
if (match(q3*q5*q7*q9*s12^2));
 redefine rule208 "1";
 $repeat = 1;
endif;
if (match(q5*q6*q8*q9*s12*s45*s53));
 redefine rule209 "1";
 $repeat = 1;
endif;
if (match(mh*q3*q5*q6*q9*s12^2));
 redefine rule210 "1";
 $repeat = 1;
endif;
if (match(mh*q6*q8*q9*s53));
 redefine rule211 "1";
 $repeat = 1;
endif;
if (match(mt*q3*q5*q6*q9*s12^2));
 redefine rule212 "1";
 $repeat = 1;
endif;
if (match(q3*q5*q6*q9*s12^3));
 redefine rule213 "1";
 $repeat = 1;
endif;
if (match(mt*q3*q7*q9*s45));
 redefine rule214 "1";
 $repeat = 1;
endif;
if (match(q4*q5*q6*q9*s12^2));
 redefine rule215 "1";
 $repeat = 1;
endif;
if (match(mh*q4*q6*q9));
 redefine rule216 "1";
 $repeat = 1;
endif;
if (match(mh*q4*q7*q9));
 redefine rule217 "1";
 $repeat = 1;
endif;
if (match(q4*q6*q9*s45));
 redefine rule218 "1";
 $repeat = 1;
endif;
if (match(mh*q3^2*q6*q9));
 redefine rule219 "1";
 $repeat = 1;
endif;
if (match(mt^2*q4*q7*q9));
 redefine rule220 "1";
 $repeat = 1;
endif;
if (match(q4*q5*q7*q9*s12^2));
 redefine rule221 "1";
 $repeat = 1;
endif;
if (match(mt^2*q3^2*q6*q9));
 redefine rule222 "1";
 $repeat = 1;
endif;
if (match(mh*q3^2*q7*q9));
 redefine rule223 "1";
 $repeat = 1;
endif;
if (match(q3^2*q5*q6*q9*s12^2));
 redefine rule224 "1";
 $repeat = 1;
endif;
if (match(q6*q7*q9));
 redefine rule225 "1";
 $repeat = 1;
endif;
if (match(q3^2*q7*q9*s45));
 redefine rule226 "1";
 $repeat = 1;
endif;
if (match(q4^2*q6*q9));
 redefine rule227 "1";
 $repeat = 1;
endif;
if (match(q4^2*q7*q9));
 redefine rule228 "1";
 $repeat = 1;
endif;
.sort
Skip;
NSkip `expr';
