---
kinematics:
  incoming_momenta: [p1,p2]
  outgoing_momenta: [p3,p4,q]
  momentum_conservation: [q,p1+p2-p3-p4]
  kinematic_invariants:
    - [s12,2]
    - [s23,2]
    - [s35,2]
    - [s45,2]
    - [s14,2]
    - [mt,1]
    - [mh,1]
  scalarproduct_rules:
    - [[p1,p1],0]
    - [[p2,p2],0]
    - [[p3,p3],mt^2]
    - [[p4,p4],mt^2]
    - [[q,q],mh^2]
    - [[p1+p2,p1+p2],s12]
    - [[p2-p3,p2-p3],s23]
    - [[p3+q,p3+q],s35]
    - [[p4+q,p4+q],s45]
    - [[p1-p4,p1-p4],s14]
