integralfamilies:

  - name: pentagon1
    loop_momenta: [k1]
    propagators:
      - ["k1",0]
      - ["k1 + p1", 0]
      - ["k1 + p1 + p2",0]
      - ["k1 + p1 + p2 - p3", 0]
      - ["k1 + p1 + p2 - p3 - p4",0]

        #  - name: pentagon1_2_10
        #    loop_momenta: [k1]
        #    propagators:
        #      - ["k1", 0]
        #      - ["k1 + p1", 0]
        #      - ["k1 + p1 + p2", 0]
        #      - ["k1 + p1 + p2 - p3",mt^2]
        #      - ["k1 + p1 + p2 - p3 - p4",mt^2]
        #
        #  - name: pentagon2
        #    loop_momenta: [k1]
        #    propagators:
        #      - ["k1", 0]
        #      - ["k1 + p1", 0]
        #      - ["k1 + p1 + p2", 0]
        #      - ["k1 + p1 + p2 - p4",mt^2]
        #      - ["k1 + p3",mt^2]
