integralfamilies:

  - name: pentagon1_4_2
    loop_momenta: [k1]
    propagators:
      - ["k1",mt^2]
      - ["p1 + k1",mt^2]
      - ["p1 + p2 + k1",mt^2]
      - ["p1 + p2 - p3 + k1", 0]
      - ["p1 + p2 - p3 - p4 + k1",mt^2]

  - name: pentagon2_2_10
    loop_momenta: [k1]
    propagators:
      - ["k1", 0]
      - ["p1 + k1", 0]
      - ["p1 + p2 + k1", 0]
      - ["p1 + p2 - p3 + k1",mt^2]
      - ["p4 + k1",mt^2]

  - name: pentagon7_3_3
    loop_momenta: [k1]
    propagators:
      - ["k1",mt^2]
      - ["p1 + k1",mt^2]
      - ["p1 - p3 + k1", 0]
      - ["p1 + p2 - p3 + k1", 0]
      - ["p1 + p2 - p3 - p4 + k1",mt^2]

  - name: pentagon9_4_3
    loop_momenta: [k1]
    propagators:
      - ["k1",mt^2]
      - ["p1 + k1",mt^2]
      - ["p1 - p3 + k1", 0]
      - ["p1 - p3 - p4 + k1",mt^2]
      - ["p1 + p2 - p3 - p4 + k1",mt^2]
