integralfamilies:

  #  - name: pentagonbox1
  #    loop_momenta: [k1,k2]
  #    propagators:
  #      - ["k1",0]
  #      - ["p1 + k1",0]
  #      - ["p1 + p2 + k1",0]
  #      - ["p1 + p2 - p3 + k1",0]
  #      - ["k2",0]
  #      - ["p1 + p2 - p3 + k2",0]
  #      - ["p1 + p2 - p3 - p4 + k2",0]
  #      - ["k1 - k2",0]
  #      - ["p1 + p2 - p3 - p4 + k1",0]
  #      - ["p1 + k2",0]
  #      - ["p1 + p2 + k2",0]

  - name: hexagonbox1
    loop_momenta: [k1,k2]
    propagators:
      - ["k1",0]
      - [" - p1 + k1",0]
      - [" - p1 - p2 + k1",0]
      - [" - p1 - p2 + p3 + k1",0]
      - ["k2",0]
      - [" - p1 - p2 + p3 + p4 + k2",0]
      - ["k1 - k2",0]
      - [" - p4 + k1 - k2",0]
      - [" - p1 + k2",0]
      - [" - p1 - p2 + k2",0]
      - [" - p1 - p2 + p3 + k2",0]
