*
* file generated by qgraf-3.5.0
*

Local loop0diagram1=

 (1)*
 glprop(1,2,-p1-p2,0)*
 fpropt(3,4,p3+q,mt)*
 vrtx(Uug,-3,p2,1,-p1-p2,-1,p1)*
 vrtx(Tth,-2,-p3,3,p3+q,-6,-q)*
 vrtx(Ttg,4,-p3-q,2,p1+p2,-4,-p4)
;
Local loop0diagram2=

 (1)*
 glprop(1,2,-p1-p2,0)*
 fpropt(3,4,-p4-q,mt)*
 vrtx(Uug,-3,p2,1,-p1-p2,-1,p1)*
 vrtx(Tth,4,p4+q,-4,-p4,-6,-q)*
 vrtx(Ttg,-2,-p3,2,p1+p2,3,-p4-q)
;

* end

