integralfamilies:

  - name: pentagon1
    loop_momenta: [k1]
    propagators:
      - ["k1",0]
      - ["p1 + k1",0]
      - ["p1 + p2 + k1",0]
      - ["p1 + p2 - p3 + k1",0]
      - ["p1 + p2 - p3 - p4 + k1",0]

  - name: pentagon2
    loop_momenta: [k1]
    propagators:
      - ["k1",0]
      - ["p1 + k1",0]
      - ["p1 + p2 + k1",0]
      - ["p1 + p2 - p3 + k1",0]
      - ["p4 + k1",0]

        #  - name: pentagon3
        #    loop_momenta: [k1]
        #    propagators:
        #      - ["k1",0]
        #      - ["p1 + k1",0]
        #      - ["p1 + p2 + k1",0]
        #      - ["p1 + p2 - p4 + k1",0]
        #      - ["p1 + p2 - p3 - p4 + k1",0]
        #
        #  - name: pentagon4
        #    loop_momenta: [k1]
        #    propagators:
        #      - ["k1",0]
        #      - ["p1 + k1",0]
        #      - ["p1 + p2 + k1",0]
        #      - ["p1 + p2 - p4 + k1",0]
        #      - ["p3 + k1",0]
